### ISSUE TITLE
Feature Request: `pop/push --to [patch]`

### ISSUE THREAD

**Issue by AlansCodeLog** [stacked-git/stgit#114]
Maybe I'm missing something but I've often found myself wanting to pop/push a bunch of stashes up to a specific one. Something like `pop current..[patch after target]` / `push [patch after current]..[target]`

I know about `-n` but that involves counting and usually I remember the name of exactly where I want to pop to and if I don't it could be autocompleted. 

I looked up if I might be able to make a command for this, but I can't find a command for something like `stg current` and `stg next/prev` don't take arguments.

**Comment by hasturkun** [comment]
`stg goto` already does this, pushing/popping until specified patch is the current one (as shown by `stg top`).

**Comment by AlansCodeLog** [comment]
Omg, thanks, I totally missed it! Sorry about that.
