### ISSUE TITLE
Include name of squashed patch in squash edit message.

### ISSUE THREAD

**Issue by topher200** [stacked-git/stgit#119]
A possible modification to consider in the `stg squash` edit message: show the squashed patch name somewhere. Possibly on the first line. E.g.:

```# squashed-patch-name is a combination of N patches```

or

```# Squashing N patches as squashed-patch-name```

The latter would be better if reusing the name of one of the patches being squashed (which I often do).

_Originally posted by @jpgrayson in https://github.com/stacked-git/stgit/issues/118#issuecomment-867903919_

**Comment by topher200** [comment]
> `# Squashing N patches as squashed-patch-name`

I like that! I see clearly how it would work if `--name` is given to `stg squash`. I'm not as sure how it would work if no `--name` is provided, because the name will be dependent on the squashed commit message (which is obviously not finalized at the point when we open the editor).

How do you expect it should work for the case where no `--name` is provided?

**Comment by jpgrayson** [comment]
Good point. The top line would need to be conditional. Probably just `# Squashing N patches` if the name is TBD.
