### ISSUE TITLE
stg commands only work in a repository's root directory

### ISSUE THREAD

**Issue by racko** [stacked-git/stgit#124]
If I use any stgit command in a subdirectory of a repository, I get
```
$ stg series
stg series: While reading log from refs/heads/my_branch.stgit:
            Not a stack log
```
(I used `stg series` just as an example.)

In the beginning I thought that I broke stgit through rebasing or something like that, but when it happened with `stg init` on a clean branch I started to dig deeper. I found that `git ls-tree <hash>`, used in
https://github.com/stacked-git/stgit/blob/097c527a40797e1b3f3a954cfc5e04987fbb61a9/stgit/lib/git/objects.py#L146
only works in the root directory of the repository:

```
repo_root $ git ls-tree c08c599ce8cfd5954c6d3f8e253d30206d65a3e9
100644 blob 333aa7325e7ae3546d534d2878759d5810fe0b8d    meta
040000 tree 4b825dc642cb6eb9a060e54bf8d69288fbee4904    patches
repo_root $ cd sub
repo_root/sub $ git ls-tree c08c599ce8cfd5954c6d3f8e253d30206d65a3e9
repo_root/sub $ echo $?
0
```

I could not find any hint in the stgit documentation that this is expected behavior.

I found that `git ls-tree --full-tree <hash>` (https://git-scm.com/docs/git-ls-tree#Documentation/git-ls-tree.txt---full-tree) always provides the expected output, even in subdirectories. But I don't know whether this would be the only fix necessary. Neither do I know whether the fix would be desired. Maybe stgit should only be used from the root directory? I would be fine with that workflow, but at least the error message should be improved.

```
$ stg --version
Stacked GIT 1.1
git version 2.30.0
Python version 3.9.1 (default, Dec 13 2020, 11:55:53) 
[GCC 10.2.0]
```

**Comment by racko** [comment]
I just tried it in a different, simpler repository and found that the problem doesn't occur there. So as another detail I'd like to mention that the repository I saw the problem in is a submodule of another repository ... not sure yet if that's relevant.

**Comment by jpgrayson** [comment]
With git submodules, if your current directory is a submodule of a more top-level repository then all git commands will operate on the submodule (sub-repository). StGit follows suit with Git, so any StGit commands issued from within a submodule directory operate on that submodule. So I believe you are experiencing intended behavior.

Note that a good reason to have StGit commands operate on the submodule is that there are valid/useful workflows where you might want to have a StGit patch queue in the submodule's repository. If StGit commands issued from within a submodule _didn't_ operate on that submodule, that would be bad behavior.

Two other things of note:

1. You can use the GIT_DIR environment variable to override Git's (and StGit's) search for the repository. E.g.:

`GIT_DIR=path/to/toplevel/.git stg series`

2. `git` has the globally available `-C <path>` command line option which overrides the current directory. StGit *does not* have such an option, but perhaps it should.

**Comment by racko** [comment]
Sorry for communicating badly: I do not expect stgit to operate on the more top-level repository. It fails to operate on the submodule when I am in a subdirectory of the submodule.

**Comment by jpgrayson** [comment]
Thanks for the clarification.

However, I am unable to reproduce any issues with running `stg` commands from either a subdirectory of a top-level repo or a subdirectory of a submodule. If you could provide the `git` and `stg` commands for a reproducible case, that would be really helpful.

Going back to your previous comment about how StGit runs `git ls-tree`, I'll note that `Repository.run()` sets the `GIT_DIR` environment variable when it runs `git` commands, so the `git ls-tree` _effectively_ runs from the top-level of the working tree.

The symptom originally reported, the "Not a stack log" error, indicates that while the StGit metadata branch exists (i.e. the `my_branch.stgit` branch), it does not contain the `meta` file (blob) which is where the key stack metadata is stored. This seems to indicate that something wrong happened to that branch. If some prior StGit command put `my_branch.stgit` into a bad state, that would be a pretty important bug to find and repair. However, if it was from Git commands you ran that's a different story.

I'm going to keep this issue closed. Please reopen if you can provide a reproducing case.
