### ISSUE TITLE
Performance: `git --diff-index --patch --binary` upon `stg new` can be a very expensive operation.

### ISSUE THREAD

**Issue by NonLogicalDev** [stacked-git/stgit#145]
I noticed that running the following has become significantly slower recently:
```
stg new <new-patch-name>
```

It seems like the command triggers `git diff-index --patch --binary` which is an extremely expensive operation on big monorepos, as it triggers an LSTAT on every single file.

However running, the following does not:

```
stg new <new-patch-name> -m "commit summary"
```

Which makes sense since, in this case the `update_commit_data`'s edit workflow is not triggered.

I think the culprit is this line, which was implemented in a recent PR: (#136)

https://github.com/stacked-git/stgit/blob/master/stgit/commands/common.py#L527

I think the intention here is to show the changed files, which is great.
But the downside of using this low level explicit command is that even if you have FSMonitor installed and configured (https://github.com/jgavris/rs-git-fsmonitor), it is not consulted, which `git diff` does use.

In our company monorepo we have 380000+ files and the operation easily takes 10-13 seconds per run.

I would propose adding a config option to avoid this operation if possible, as its output is purely informational.

The configuration can be something like this:
* `stgit.new_diff = "diff-index"`
* `stgit.new_diff = "diff"`
* `stgit.new_diff = "disabled"`

### STG Version:

```
Stacked Git 1.1+40.g1b20.dirty
git version 2.31.1
Python version 3.9.6 (default, Jun 29 2021, 05:25:02)
[Clang 12.0.5 (clang-1205.0.22.9)]
```

### Platform:

Intel/Darwin/MacOS

**Comment by NonLogicalDev** [comment]
Hey @topher200, I see you are the author of the last change related to this. Do you have any thoughts?

**Comment by topher200** [comment]
This option is already behind a flag, the diff is only invoked if one of these is true:
- `stg new --verbose`
OR
- `stg new` with this config setting:
```
~/.gitconfig

[commit]
  verbose = 1
```

My guess -- `commit.verbose` is set in your `.gitconfig`. Try removing that and seeing if the issue goes away!

**Comment by topher200** [comment]
Hmmm... I might have spoken too soon. I tried again locally and discovered that I still get the diff in `stg new` even without `commit.verbose`. That would be a bug!

We have a test case which checks that the verbose setting adds a diff: https://github.com/stacked-git/stgit/blob/1b2058a91b7ed920952ea99b5140c60b8c7cdd1b/t/t1003-new.sh#L97. As part of fixing this bug we should add the inverse test case (no `commit.verbose` and no `--verbose` == no diff).

I'm about to go away on vacation -- not sure if I'll be able to address this before next week. If it's not fixed when I get back I will fix it.

**Comment by topher200** [comment]
btw -- this was the PR which added this feature: https://github.com/stacked-git/stgit/pull/122

It includes details on what the various options should do.

**Comment by NonLogicalDev** [comment]
@topher200 Thank you for the insights, I do have `commit.verbose` turned on.

That said I feel like it is best to keep party with standard git tools if we are using standard git config option like `commit.verbose`.
Since running `git commit --allow-empty` does not LSTAT all files. Which is why I am suggesting allowing the user to configure the behavior to their needs. 

Your approach totally works on reasonably sized repos, but I would love to make life a bit easier for us folks that work on gigantic monorepos. =]

I'll see if I can add a new config option to allow reverting to old behavior.

**Comment by topher200** [comment]
Maybe the error here was to overload `commit.verbose`. Perhaps we should add a new config option of `stgit.verbose-new` or `stgit.new-verbose` and not borrow `commit.verbose`. 

(this statement ignores the probable bug I mentioned in https://github.com/stacked-git/stgit/issues/145#issuecomment-889431486)

**Comment by NonLogicalDev** [comment]
@topher200 I feel like if going even further meta, it is a bit of a misnomer that Git does not have a way to generate a diff between the current state of worktree and the topmost commit that uses FSMonitor correctly.

I guess it could be possible to do 
```
# Staged_Result
git diff --cached
# Unstaged_Result
git diff
# compute Staged_Result + Unstaged_Result using only diffs.
```

But that feels like a ripe ground for all kinds of interesting bugs.

**Comment by NonLogicalDev** [comment]
Opfff, this is painful, I was hoping that `git diff HEAD` would perform better. But it is just as bad performance wise.

**Comment by NonLogicalDev** [comment]
(continue: https://github.com/stacked-git/stgit/issues/145#issuecomment-889440471)

Seems like it is possible:

```bash
$ git diff --cached
diff --git a/src/path/to/file/test.txt b/src/path/to/file/test.txt
new file mode 100644
index 000000000000..19d9cc8584ac
--- /dev/null
+++ b/src/path/to/file/test.txt
@@ -0,0 +1 @@
+staged
```

```bash
$ git diff 
diff --git a/src/path/to/file/test.txt b/src/path/to/file/test.txt
index 19d9cc8584ac..b97ac3c15ee1 100644
--- a/src/path/to/file/test.txt
+++ b/src/path/to/file/test.txt
@@ -1 +1,2 @@
 staged
+unstaged
```

```
$ combinediff -p 1 <(git diff --cached) <(git diff)
diff -u b/src/path/to/file/test.txt b/src/path/to/file/test.txt
--- b/src/path/to/file/test.txt
+++ b/src/path/to/file/test.txt
@@ -0,0 +1,2 @@
+staged
+unstaged
```

**Comment by topher200** [comment]
> Hmmm... I might have spoken too soon. I tried again locally and discovered that I still get the diff in stg new even without commit.verbose. That would be a bug!

I added a new test case to show that there is no bug; if there's no `--verbose` we do not get a diff. PR: https://github.com/stacked-git/stgit/pull/146

This matches the findings from https://github.com/stacked-git/stgit/issues/145#issuecomment-889435003 ("I do have commit.verbose turned on")

I think we were past this issue but I wanted to add it to the test suite to ensure there's no issue now and there's no regression in the future.

**Comment by topher200** [comment]
@NonLogicalDev If it's helpful, this is the function we're using to generate the diff:

https://github.com/stacked-git/stgit/blob/fe09108c9ab8f776a67ba0e58f88aeae9cf2c3c5/stgit/commands/common.py#L527

https://github.com/stacked-git/stgit/blob/fe09108c9ab8f776a67ba0e58f88aeae9cf2c3c5/stgit/lib/git/iw.py#L290-L303

I dumped `locals()` during a test run of `stg new --verbose`. Nothing interesting there:
```
'self': <stgit.lib.git.iw.IndexAndWorktree object at 0x7f946cbd67c0>, 
'tree': Tree<sha1: 9ccdf12d2f08d43216608415d3fb88e119a70bb6>, 
'diff_opts': (), 
'pathlimits': (), 
'binary': True, 
'stat': False
```

**Comment by jpgrayson** [comment]
I've gone over the conversation here a few times. Here's a summary of the findings:

* The diff performed for `stg new -v` is expensive for repos with many files
* There are forms of `git diff` that leverage fsmonitor and are thus less expensive
* It's not clearly appropriate for StGit to use those forms of `git diff` because we want to see staged and unstaged diffs
* The performance impact on `stg new` can be mitigated by not configuring `commit.verbose`.

I just made a change in 21c09b7 to not show binary diffs with `stg new -v`. This could also cause a performance problem anytime a large binary file was changed.

I'm not seeing any solid next steps for this problem. Wondering what @NonLogicalDev and @topher200 think about closing this issue?

**Comment by NonLogicalDev** [comment]
I think the only change that should be made is to stop piggy backing on `commit.verbose` configuration as that can be somewhat unexpected behavior. 

But that is likely a separate issue. In regards to performance I guess we should see if we get any more reports. But allowing turning off this feature only for stg would go a long way.

**Comment by topher200** [comment]
I think this issue can be closed!

**Comment by NonLogicalDev** [comment]
Closing this one for now, we can reopen it if one of us has time to investigate more, or if someone else will come across this issue.
