### ISSUE TITLE
stg mail should use patch numbering for a single patch if a cover note is specified

### ISSUE THREAD

**Issue by dhowells** [stacked-git/stgit#156]
If "stg mail" is given a single patch and a cover letter to send, it doesn't insert the usual patch numbering into the subject fields; however, I would expect the cover to be 00/01 and the patch to be 01/01.  Can it be made to do this - or at least take a config option to make this the default?

**Comment by jpgrayson** [comment]
In StGit 2.0, `stg email format` has the expected behavior. Example:

```shellsession
$ stg email format --cover-letter --output-directory=out a-patch
out/0000-cover-letter.patch
out/0001-a-patch.patch
$ grep -h "Subject:" out/*.patch
Subject: [PATCH 0/1] *** SUBJECT HERE ***
Subject: [PATCH 1/1] a-patch
```
