### ISSUE TITLE
feature request: `stg cherry-pick`

### ISSUE THREAD

**Issue by smoofra** [stacked-git/stgit#164]
## New Feature Request

I often find myself wanting to convert a pre-existing git commit into a stg patch.   This isn't so hard to do, one can 
`git format-patch` and then `stg import`, but it would be convenient if stg had a command to do it in one step.

**Comment by lkraav** [comment]
What's wrong with `stg pick`?

**Comment by smoofra** [comment]
oops, nothing is wrong with it.  
that's just what I need￼

**Comment by NonLogicalDev** [comment]
@smoofra Would it be alright to close the issue?

**Comment by smoofra** [comment]
Yup, thanks
