### ISSUE TITLE
"stg repair" after "git rebase" resets HEAD incorrectly

### ISSUE THREAD

**Issue by mandolaerik** [stacked-git/stgit#170]
When a stg inconsistency is caused by an external rebase, `stg repair` seems to do a soft reset to the git merge base. I expect that both `stg diff` and HEAD would be unaffected by `repair`.

A workaround is to run `git reset --soft @@{1}` after the repair.

Reproducer script: [repro.sh.txt](https://github.com/stacked-git/stgit/files/7679088/repro.sh.txt)

**Comment by jpgrayson** [comment]
I believe this works with the repair I just made for #163 (https://github.com/stacked-git/stgit/commit/879b5c26b2529c8ae579c8c7588f99772a893419)

With that change to `stg repair`, the final state is:

- Worktree and index are clean
- "Patchified" patches "a" and "b-1" are applied
- Existing patch "b" is unapplied.

I'd like to know whether the updated behavior of `stg repair` is okay for you and this use case?

**Comment by mandolaerik** [comment]
Thanks, that resolved my problems! Closing.

**Comment by jpgrayson** [comment]
Great! Thanks for the reproducing script and for helping verify the new behavior, @mandolaerik!
