### ISSUE TITLE
Should stg edit recompute the patch name?

### ISSUE THREAD

**Issue by jkleckner** [stacked-git/stgit#172]
I find myself continually updating a particular patch and the description followed by renaming the patch to reflect the new summary line.

What do people think about changing the default action of `stg edit` updating the patch name as the default with possibly a `--no-rename` argument to suppress that (which I personally don't think people would bother about)?

**Comment by lkraav** [comment]
I've thought about this, and lean towards "yes".

**Comment by jkleckner** [comment]
While looking into the code, I noted that the patch name can easily be modified by editing the first line in the editor buffer beginning with `Patch: name-to-display`.

So this change is not needed IMHO.
