### ISSUE TITLE
Option to get the commit id of an stg patch?

### ISSUE THREAD

**Issue by larsks** [stacked-git/stgit#173]
I'm looking for a simple mechanism to convert an stg patch name into a commit id.

The best I've come up with so far is to `stg goto` the patch, and then use `git rev-parse HEAD` to get the commit id, but of course this requires iterating through the patch stack and updating the work tree which seems like a lot of work to extract a piece of metadata which is already stored in the patch list.

The obvious subcommand for this would be `stg show`, but that doesn't currently have any option to output only the commit id.

Assuming I'm not missing something obvious, would it make more sense to:

- Add a flag (e.g., `-q`) to `stg show` causing it to emit only the commit id, or
- Add a `--format` option that is simply passed through to `git show`?

**Comment by jpgrayson** [comment]
This is what `stg id` does. Based on your question, I think you might just have been unaware of `stg id`. Please let me know if there is more to your question.

**Comment by larsks** [comment]
I was totally unaware of `stg id`, and somehow missed it in the help output despite looking at it multiple times (I think because I was looking for the word "commit"). Sorry for the noise!

**Comment by jpgrayson** [comment]
No problem! Thanks for using StGit.
