### ISSUE TITLE
A way to see code changes from stg log?

### ISSUE THREAD

**Issue by jkleckner** [stacked-git/stgit#198]
`stg log --diff` will show the changes made to the repo as transactions.

Has anyone crafted a way to show the diffs made to the code much like `git log --patch` does?

**Comment by jpgrayson** [comment]
`stg show -AU` will show the diffs of all applied and unapplied patches in a `git log --patch`-like format. I think this is what you want.

Another potentially interesting command is `stg log --diff <patch>`, which shows how the StGit metadata of a patch has changed over time.

**Comment by jkleckner** [comment]
@jpgrayson  Yes, this is exactly what I want, thanks again!
