### ISSUE TITLE
Diffing a commit from Emacs stgit mode does not work with the Rust version

### ISSUE THREAD

**Issue by clillies** [stacked-git/stgit#202]
Using the Rust version, and the latest stgit.el, showing the current commit does not work.
Standing on a commit, I press '=', but nothing happens.

```
GIT commit 4b5e435816ff40d1e03add9ac974b279a4030435
> stg --version
Stacked Git 2.0.0-beta.2
Copyright (C) 2005-2022 StGit authors
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
SPDX-License-Identifier: GPL-2.0-only
git version 2.31.1
```

**Comment by jpgrayson** [comment]
I think I found the issue. When composing arguments for `stg show`, `stgit.el` inserts a `--` separator before the patch name. In StGit 2.0.0, `stg show` was enhanced to optionally take pathspec arguments after the `--` separator whereas in StGit <2, the separator was optional and patch names could come before or after it.

StGit <2.0 usage:
`stg show [options] [--] [patchrange]...`

StGit >=2.0 usage:
`stg show [options] [patchrange]... [-- <pathspec>...]`

I will push a repair for this issue. Thanks for the issue report, @clillies.

**Comment by clillies** [comment]
Thanks for fixing @jpgrayson, but the fix did not work for me.
I needed to remove also the other "--" on line 2410.

**Comment by jpgrayson** [comment]
Thanks for this follow-up, @clillies. I've pushed the second change you identified. Please let me know if you see any other problems with `stgit.el`.

**Comment by clillies** [comment]
Thank you very much Pete.
No other problem at the moment, full steam ahead with the Rust-stgit!
