### ISSUE TITLE
Building manpages for StGit 2 takes ages

### ISSUE THREAD

**Issue by Necoro** [stacked-git/stgit#229]
Hi,

there seems to be a problem with the makefile in regards to generating the manpages (`make -C Documentation all`). While compiling the program took 1.5 minutes, generating the documentation now runs for 30mins.
When I look into `htop`, I notice that a `cargo` process is running all the time in parallel:
![stgit_doc](https://user-images.githubusercontent.com/68708/200286069-ffb915ec-9f50-42a5-b746-ed1200a6fece.png)

I had a look into the Makefile but couldn't easily spot the problem. It seems that it is somehow computing the version number over and over and over again.

**Comment by jpgrayson** [comment]
Thank you also for pointing out this issue, @Necoro. I've modified `Documentation/Makefile` to avoid the pathological case you observed as well as to improve some other make performance warts.
