### ISSUE TITLE
Claim of "statically linked binary" is wrong

### ISSUE THREAD

**Issue by Necoro** [stacked-git/stgit#230]
The `README` states, that _StGit compiles to a statically linked executable_.
That is not true: besides the obvious dependency on glibc, I see dynamic links to `libgit2`, `libcurl` and `libbz2` (maybe more, haven't checked all of them).

Please change the README in that regard and add correct dependency infos. I also had to check the source code to see if the runtime dependency on `git` is still needed, or whether all has been replaced by using `libgit2`. (Result: yes, it is still needed).

**Comment by jpgrayson** [comment]
Thanks for this issue report, @Necoro. You are right that the `stg` executable is not statically linked. I've made some changes in `README.md` that hopefully tell the story more correctly.
