### ISSUE TITLE
Add `stg branch --cleanup` as `see-also` section to `stg init` man page

### ISSUE THREAD

**Issue by przemo-hemmersbach** [stacked-git/stgit#233]
As in title. stg branch could be added to man page for stg init.
If PR would be accepted I can create one, but I failed to locate docs for stg-init in source code. Where is it?

**Comment by jpgrayson** [comment]
The man pages are generated from the strings provided to `clap::App.long_about()` / `.about()` and `clap::Arg::long_help()` / `.help()` calls.

So to improve the `stg-init(1)` man page, a `.long_about()` call in `src/cmd/init.rs` needs to be added.

I am noticing that I failed to port any of the long about from the Python implementation of `stg init` into the Rust implementation. I will correct that issue and add a statement about `stg branch --cleanup` while I'm at it. Please submit a follow-on PR if there are any further changes you'd like to see in the `stg init` documentation.

Thanks for pointing out this issue, @przemo-hemmersbach!
