### ISSUE TITLE
How update old branches that give error: Malformed metadata (expected version 4)

### ISSUE THREAD

**Issue by jkleckner** [stacked-git/stgit#235]
I have some old branches that give the error: `error: Malformed metadata (expected version 4)`

What would be the best way to update them to work with the new stgit?

**Comment by jpgrayson** [comment]
StGit 2.0 is only able to upgrade from stack metadata version >= 4, which was introduced in StGit 1.0. So your old branches were ostensibly initialized using StGit <1.0.

The easiest path forward is to upgrade these branches using StGit 1.5. Stack upgrade can be triggered for all branches within a repository by running `stg branch --list`.

You can run StGit 1.5 pretty easily by using a clone of the stgit repository. Here are the complete steps:

```shellsession
$ git clone --depth=1 --branch v1.5 https://github.com/stacked-git/stgit.git path/to/stgit-1.5
$ PYTHONPATH=path/to/stgit-1.5 python -m stgit version
$ cd path/to/repo-to-upgrade
$ PYTHONPATH=path/to/stgit-1.5 python -m stgit branch --list
$ rm -rf path/to/stgit-1.5
```
---

N.B. it would be possible add code to StGit 2.x to be able to upgrade from these older stack metadata formats, but I wanted to limit the scope of the Rust implementation and I thought compatibility with StGit 1.x would be sufficient. I'm hoping the above upgrade path will be sufficient for users jumping directly from StGit <1.0 to StGit 2.x.

**Comment by jkleckner** [comment]
@jpgrayson Thank you that worked perfectly!  I ran into this when cleaning up some very old branches.

**Comment by AndreRH** [comment]
Since #318 was merged this automagically works now :)
