### ISSUE TITLE
`stg new` deriving patch name *after* writing commit message?

### ISSUE THREAD

**Issue by martijnthe** [stacked-git/stgit#239]
First of all, thanks so much for stgit 2.x! It's so fast, I love it :heart: :100: 

I noticed that the generation of the patch name from the commit message with 2.x has changed a bit.
I use a `patchdescr.tmpl` file. Note the empty first line: it's a blank for the title of the changeset:
```


 ### Issues Addressed

 ### Summary of Changes

 ### Test Plan

```

### v1.x behavior

Before in v1.x, if I would run `stg new`, my editor would be ran with a copy of the template, I would add the title in the first line, etc. and save it. Stgit would then derive the patch name from the first line (the title). This was great and very useful.

### v2.x behavior

Now, with v2.x, if I run `stg new`, the patch name gets generated based off the *empty template* (always ends up being `issues-addressed`). So, the name derivation happens *before* the editor gets launched and no longer *after* saving the fill-out template.

Workflow-wise, I'm now forced to edit both the title as well as the name of the patch (defeating the purpose of the automatic patch name derivation).

### Questions
- Is this intentional?
- If so, is there a work-around to get the old behavior?

### Context
```
$ stg --version
Stacked Git 2.0.2
Copyright (C) 2005-2022 StGit authors
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
SPDX-License-Identifier: GPL-2.0-only
git version 2.37.2
```

**Comment by jpgrayson** [comment]
Thanks for writing this issue repot, @martijnthe. Much appreciated.

I agree that the behavior could be improved in this scenario. I think what we would prefer is if the `.stg-edit.txt` did not have a pre-populated `Patch:` header in this case. I.e. instead of seeing:

```
Patch:  issues-addressed
Author: Author <author@example.com>
Date:   2022-11-26 11:44:42 -0500



 ### Issues Addressed

 ### Summary of Changes

 ### Test Plan

# Please enter the message for your patch. Lines starting with
# '#' will be ignored. An empty message aborts the new patch.
# The patch name and author information may also be modified.
```

you'd see this:

```
Patch:  
Author: Author <author@example.com>
Date:   2022-11-26 11:44:42 -0500



 ### Issues Addressed

 ### Summary of Changes

 ### Test Plan

# Please enter the message for your patch. Lines starting with
# '#' will be ignored. An empty message aborts the new patch.
# The patch name and author information may also be modified.
```

In the latter, you could either choose to fill-in your own patch name explicitly in the `Patch:` header, or leave that blank and let the patch name be auto-derived from the message summary after saving and exiting.

I believe StGit could be changed to have this behavior without too much trouble.

**Comment by martijnthe** [comment]
Wow! Thanks so much for the quick fix! I'll try it out on Monday.

**Comment by martijnthe** [comment]
@jpgrayson it's been working great! Thanks again.

**Comment by jpgrayson** [comment]
Thank you for testing this fix. I'm glad we could get this detail corrected.
