### ISSUE TITLE
Support `@{-N}` for specifying branches

### ISSUE THREAD

**Issue by liuw** [stacked-git/stgit#246]
git-checkout(1) supports `@{-N}`, with a shorthand `-` equivalent to `@{-1}`. My most used one is `git checkout -` to switch back and forth between two branches.

Stgit does not support it yet. `stg branch -` complains `-` is not a valid branch name. That's because it calls `git_branch_is_valid` directly. I'm not sure how difficult it is to change the code, but `libgit2` does support looking up the branch -- there is a function called `find_branch` under the `Repository` type.

At the end of the day, I don't think this is a big deal. Stgit users, when switching branches, can always use `git-checkout` directly.

**Comment by jpgrayson** [comment]
Thanks for this suggestion, @liuw. I've implemented it.

This ended up having a nice symmetry with the new patch locator syntax just introduced in aa7a91d922b66d934d189648b1d058a3b64465d1. In addition to being available for switching branches with `stg branch -` or `stg branch @{-2}`, I've applied branch locators in most contexts where StGit takes branch arguments. So, for example, `stg series -b -` or `stg pick -B @{-1} ...` also work.
