### ISSUE TITLE
stg branch --clone breaks if there was previously a matching stgit branch

### ISSUE THREAD

**Issue by larsks** [stacked-git/stgit#290]
Some time earlier in the week, I made a temporary clone of an stgit managed branch:

```
stg branch --clone work
```

I ended up switching back to the primary branch and deleting the old one:

```
git checkout devel
git branch -D work
```

Just now, I tried creating a stgit clone with the same name:

```
stg branch --clone work
```

And that failed because of artifacts left over from the previous branch:

```
error: Reference "refs/stacks/work" was not supposed to exist when writing it with value Peeled(Sha1(b9001282cc467a07123c65d4eea0b00892859913)), but actual content was Peeled(Sha1(635221571b89fe943b2532c5dfecb18a72a7a5a0))
```

1. Is stgit expected to fail in this situation? Should it just replace the target reference, since the associated branch no longer exists? Should it by default *not* replace it, but offer a `--force` option or similar to make it work?

2. If it's expected to fail, maybe we could make that error message a little more user friendly? I was trying to think of appropriate phrasing, but I think the answers to the first question will provide some guidance for what it should say.

**Comment by jpgrayson** [comment]
Thanks for this issue report, @larsks.

I had not explicitly considered what StGit should do in this situation where a StGit branch is only partially deleted using `git branch -D` and then that branch name is reused.

My instinct is that StGit should succeed in this circumstance, but perhaps show a warning.

If a user explicitly deletes a branch using `git`, it seems reasonable for StGit to respect that action. This would mean, as you suggest, StGit should delete/reset the stale `refs/stacks/<branch>` ref when it finds `refs/heads/<branch>` is missing.

The warning would be something of the effect "StGit-enabled branch seems to have been deleted outside of StGit; use `stg branch` to manage StGit-enabled branches".
