### ISSUE TITLE
`stg init` fails in a fresh repo

### ISSUE THREAD

**Issue by achronop** [stacked-git/stgit#292]
```
➜  repos mkdir random
➜  repos cd random 
➜  radom git init
Initialized empty Git repository in /xxx/repos/random/.git/
➜  radom git:(master) stg init
stg init: master: no such branch
➜  radom git:(master) 
➜  radom git:(master) stg -v
Stacked Git 1.5
git version 2.39.2
Python 3.11.2
```

On Fedora 37

**Comment by jpgrayson** [comment]
A just-initialized git repository does not have any commits, but a branch is a reference to a commit. So a new repo without any commits, but with `HEAD` pointing to `refs/heads/master` is said to have an "unborn" branch. StGit requires that its stacks are associated with fully born branches. I have not thought too deeply about how StGit could associate a stack with an unborn branch, but my hot-take is that while it is probably doable, it's probably not doable at a reasonable cost for the small amount of value. I'm open to different assessments and ideas for different StGit behavior with unborn branches.

Also, I see you're running an older StGit release. The unborn branch behavior is the same in the latest 2.x releases, but if anything was going to change regarding unborn branches, it would be done for the 2.x/Rust implementation of StGit. StGit 1.x is not being maintained anymore.

**Comment by achronop** [comment]
Thank you for the explanation. It worked after the first commit. Regarding the release, unfortunately, this is the latest version in this distro. I will try to update it manually.

Feel free to close the issue if you believe it is not worth spending the time on. Maybe, you can simply document the behavior or point out the case in the return message, if it is discoverable programmatically.

**Comment by jpgrayson** [comment]
One last note on this: in StGit 2.x, the error message is perhaps a little better:

```
$ git init repo
...
$ cd repo
$ stg init
error: branch `refs/heads/main` is unborn
```
