### ISSUE TITLE
Assertion failure when creating a branch

### ISSUE THREAD

**Issue by dhowells** [stacked-git/stgit#323]
bash> RUST_BACKTRACE=full stg branch --create cachefiles-fixes v6.4-rc2
info: Recording `v6.4-rc2` as parent branch
thread 'main' panicked at 'assertion failed: matches!(reference.name().category(),\n    Some(Category :: LocalBranch | Category :: RemoteBranch))', src/wrap/branch.rs:18:9
stack backtrace:
   0:     0x56248aa72a9a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h23e12af75169d6b9
   1:     0x56248aa9995e - core::fmt::write::h86f05b6e21be6376
   2:     0x56248aa6e715 - std::io::Write::write_fmt::h3fa15e9b7445977a
   3:     0x56248aa72865 - std::sys_common::backtrace::print::h584ee38769ddfb5d
   4:     0x56248aa741ef - std::panicking::default_hook::{{closure}}::hc158f42604c87d65
   5:     0x56248aa73f2b - std::panicking::default_hook::h4705b9e080ca103c
   6:     0x56248aa748f9 - std::panicking::rust_panic_with_hook::h16160c0d99adaf2e
   7:     0x56248aa74652 - std::panicking::begin_panic_handler::{{closure}}::hd2661207f627a7a1
   8:     0x56248aa72f4c - std::sys_common::backtrace::__rust_end_short_backtrace::hbb3515718de50010
   9:     0x56248aa743a2 - rust_begin_unwind
  10:     0x56248a66a123 - core::panicking::panic_fmt::hc92854c3657c009b
  11:     0x56248a66a1bd - core::panicking::panic::h7669bffd2f8608fb
  12:     0x56248a8424f6 - stg::wrap::branch::Branch::wrap::hdae33d5a7461a423
  13:     0x56248a7504c5 - stg::cmd::branch::create::dispatch::h2fcb83c2f15890ac
  14:     0x56248a6dd665 - stg::cmd::branch::run::h92268183a5a06acb
  15:     0x56248a70df0c - stg::execute_command::h48024ae29cdb6d9d
  16:     0x56248a70d449 - stg::main::h564684af0f9a3a4b
  17:     0x56248a725a93 - std::sys_common::backtrace::__rust_begin_short_backtrace::h290f6a3b8e054857
  18:     0x56248a6787f9 - std::rt::lang_start::{{closure}}::h9b9a7cf2e8b2c253
  19:     0x56248aa66b9c - std::rt::lang_start_internal::hbb0ceecca36c028f
  20:     0x56248a710345 - main
  21:     0x7fc55d62808a - __libc_start_call_main
  22:     0x7fc55d62814b - __libc_start_main@@GLIBC_2.34
  23:     0x56248a66a765 - _start
  24:                0x0 - <unknown>

commit e87737e83a970abb2193f0c6a0b45ec00078d282 ("ci: ensure perl tty deps are installed") is top.

**Comment by jpgrayson** [comment]
This issue is closely related to #317, which was fixed in v2.2.4. The fix for #317 also fixed branching based on a tag.

Could retry this with either the v2.2.4 release or HEAD and make sure it works for you too?

**Comment by dhowells** [comment]
That seems to work.
