### ISSUE TITLE
More .deb versions needed

### ISSUE THREAD

**Issue by AndreRH** [stacked-git/stgit#324]
Hi,

just wanted to leave the remark, that the freshly created .deb file won't work on older Ubuntu versions, output with 20.04:

`stg: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by stg)
stg: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by stg)
stg: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by stg)
`

**Comment by jpgrayson** [comment]
Thanks for pointing this out, @AndreRH. I appreciate you giving the package a try.

I've got a change in the works that will package fully statically linked `stg` executables. I'm using the `x86_64-unknown-linux-musl` target for this. This should make these packages maximally portable.

I'm also looking at producing x86 (32-bit) and aarch64 packages, also using static linking with musl.

**Comment by AndreRH** [comment]
That works, thanks!
