### ISSUE TITLE
Can't create a patch from emacs

### ISSUE THREAD

**Issue by clillies** [stacked-git/stgit#342]
**Stacked Git 2.3.0 (09baa9e4b)**
When creating a new patch from emacs, with **stgit-new**, the command seems to create
a new patch, but the subsequent **stg series** done by the Emacs mode fails, with the error.
**if: Syntax error in output from stg series**.

When checking from the command line, the new patch was created, but since
patches can't be listed from the StGit emacs mode is in practice broken if there is a patch in the series.

**Comment by clillies** [comment]
I think the problem in parsing the output from stg series from Emacs is that a line can start with a star '*'.
Adding a star to the pattern on line 729 seemed to do it:

```
diff --git a/contrib/stgit.el b/contrib/stgit.el
index 73ad75fb..d10214fa 100644
--- a/contrib/stgit.el
+++ b/contrib/stgit.el
@@ -726,7 +726,7 @@ using (make-hash-table :test 'equal)."
                             (match-string 0))))
             (while (not (eobp))
               (unless (looking-at
-                       "\\([0 ]\\)\\([>+-]\\)\\( \\)\\([^ ]+\\) *[|#] \\(.*\\)")
+                       "\\([*0 ]\\)\\([>+-]\\)\\( \\)\\([^ ]+\\) *[|#] \\(.*\\)")
                 (error "Syntax error in output from stg series"))
               (let* ((state-str (match-string 2))
                      (state (cond ((string= state-str ">") 'top)
```

**Comment by jpgrayson** [comment]
Thanks for reporting this and suggesting the fix, @clillies.

BTW, I have been working on magit-stgit recently. It will likely be a while until I push changes, but my hope is for it to supersede stgit.el someday.

**Comment by clillies** [comment]
Thanks for the quick response and action! I'll check out magit-stgit.
