### ISSUE TITLE
Bash tab completion for patch names broken

### ISSUE THREAD

**Issue by bonsairobo** [stacked-git/stgit#349]
I noticed this in 2.2.4. Still broken on 2.3.0. I recall this used to work for me but I don't remember which version I started on.

**Comment by jpgrayson** [comment]
Works for me. For example, `stg series <TAB>` and `stg goto <TAB>` complete patch names as expected.

Is there a particular subcommand that is problematic? Is it possible that the `stg` bash completion script is from a different version of StGit than the `stg` executable?

I'll need some additional detail in order to reproduce the problem.

**Comment by bonsairobo** [comment]
None of the commands autocomplete for me.

> Is it possible that the stg bash completion script is from a different version of StGit than the stg executable?

I'm not sure what that means TBH. I install from source to `~/.local/share`.

**Comment by jpgrayson** [comment]
>> Is it possible that the stg bash completion script is from a different version of StGit than the stg executable?

> I'm not sure what that means TBH. I install from source to ~/.local/share.

I mean that the bash completion script, which would ostensibly be found at `~/.local/share/bash-completion/completions/stg` comes from StGit version X whereas the executable `~/.local/bin/stg` comes from StGit version Y.

When you install from source, are you using `cargo install --path=.` or `make install-all`? The former will only install the `stg` executable (to `~/.cargo/bin`; the latter installs completion scripts, man pages, and contrib scripts in addition to the `stg` executable.

> None of the commands autocomplete for me.

This strongly implies that there is something wrong with how the `stg` bash completion script is installed in your environment. There may be multiple versions of the completion script in different paths (e.g. `/usr/share/bash-completion` and `~/.local/share/bash-completion`. Or it is possible that your `.bashrc` or `.profile` is sourcing the completion script directly. Or maybe the bash completion script isn't installed at all.

**Comment by bonsairobo** [comment]
Ah that's my fault, I just didn't continue reading the "Full Installation" part of your docs.

**Comment by bonsairobo** [comment]
OK I got it working. Thanks for the help!
