### ISSUE TITLE
Missing sanity checks in stg uncommit

### ISSUE THREAD

**Issue by proski** [stacked-git/stgit#360]
Sanity checks should be mandatory in all commands that modify the state of the repository. It appears that `stg uncommit` doesn't perform some checks, so it produces a result that the next command rejects. Here's my actual session:
```
proski@ins1:~/src/mono$ stg uncommit
> fix-sending-responses-from
proski@ins1:~/src/mono$ stg pop
error: HEAD and stack top are not the same. This can happen if you modify the branch with git. See `stg repair --help` for next steps to take.
proski@ins1:~/src/mono$ stg version
Stacked Git 2.3.1
Copyright (C) 2005-2022 StGit authors
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
SPDX-License-Identifier: GPL-2.0-only
git version 2.34.1
```

**Comment by jpgrayson** [comment]
Thanks for this issue report, @proski. Agreed that `uncommit` should not lead to this kind of outcome.

It would be helpful to know more about the state of the repo and the StGit stack prior to the `stg uncommit` call that led to this situation since this scenario often works without issue. In other words, without a reproducing case, it is not immediately clear what extra checks might need to be performed to avoid this outcome.

**Comment by proski** [comment]
This script demonstrates the problem:

```
#! /bin/sh

# Run in an empty directory!

set -e

export GIT_CONFIG_GLOBAL=/dev/null
export GIT_CONFIG_SYSTEM=/dev/null

rm -rf .git testfile

git init -b main
git config user.name User
git config user.email user@us.er

echo "data1" >testfile
git add testfile
git commit -a -m "Commit 1"
echo "data2" >testfile
git commit -a -m "Commit 2"
echo "data3" >testfile
git commit -a -m "Commit 3"
stg uncommit
echo "data4" >testfile
git commit -a -m "Commit 4"
echo "Running 'stg uncommit'"
stg uncommit
echo "Running 'stg pop'"
stg pop
```

The error is reported by `stg pop`. However, the second `stg uncommit` should have detected the issue.

**Comment by jpgrayson** [comment]
This reproducing case is much appreciated, @proski. I will get this figured out and fixed.
