### ISSUE TITLE
"recursive alias" error when aliasing st = status

### ISSUE THREAD

**Issue by Infinoid** [stacked-git/stgit#371]
I am used to an older (Debian) version of `stg`, where `stg st` is short for `stg status`.  I recently updated to 2.3.2 and found that this shorthand no longer works.

```
% stg st
error: unrecognized subcommand 'st'

  tip: a similar subcommand exists: 'status'

Usage: stg [OPTIONS] <command> [...]
       stg [OPTIONS] <-h|--help>
       stg --version

For more information, try '--help'.
```

I read through the manpage, saw the `stgit.alias.*` section, and decided to try it.  But it says the alias is recursive?

```
% git config --global stgit.alias.st status
% stg st
error: recursive alias `st`
% stg help | grep ^..st
  st          Alias for `stg status`
  status      Alias for shell command `git status -s`
```

It's an alias to an alias, but it's not recursive.

After some more RTFMming, I tried this, which works as expected:

```
git config --global stgit.alias.st '!git status -s'
```

But along the way, I was quite confused and misled by that "recursive alias" error message.

**Comment by Infinoid** [comment]
Thinking some more, I guess what I mean is that it's not *infinitely* recursive.

**Comment by Infinoid** [comment]
I honestly hadn't realized that `status` was an alias until I read the `stg help` output.  The "recursive alias" error didn't make sense to me until I realized this.

If the error said "aliases cannot refer to other aliases", then I would have understood it more quickly.  But otherwise, I think this issue could be closed as "user error".  Some limited recursion would have been nice, but not a big deal now that I understand how `status` is implemented.

**Comment by jpgrayson** [comment]
After taking another look at this, I think that leaving things as-is is the right thing to do.

Regarding the "recursive alias" error message: this is the same error message Git uses for the the same cause.

Regarding special-casing the built-in aliases: those aliases can be overridden in the user config, so ultimately those aliases are not actually special.

Bottom line, not sure how to make the situation materially better.

**Comment by arthurp** [comment]
I ran into exactly this issue and the way I ended up solving this is by finding this issue. I think it would be worth documenting this in the `stg` man page. That way searching the docs for "recursive" in one of the obvious places brings up the solution.

To put my money where my mouth is, here is a patch:
```diff
diff --git a/Documentation/stg.txt b/Documentation/stg.txt
index 20b75ce2..98a03465 100644
--- a/Documentation/stg.txt
+++ b/Documentation/stg.txt
@@ -259,6 +259,10 @@ running `git rev-parse --show-prefix` from the original current directory. See
 linkgit:git-rev-parse[1].
 +
 Aliases that would hide existing StGit commands are ignored.
++
+Some `stg` commands (such as `status`) are implemented as aliases. This means that the 
+error message `recursive alias` may mean an alias in the user configuration points to 
+internal `stg` alias that does not appear in the user configuration.
 
 stgit.autoimerge::
   When set to 'true', if conflicts occur when pushing a patch, linkgit:git-mergetool[1]
```
