### ISSUE TITLE
stg refresh hides output of precommit hook

### ISSUE THREAD

**Issue by larsks** [stacked-git/stgit#418]
Using Stacked Git 2.4.3 (3ff7bc2c5), I ran into the following behavior:

```
$ stg refresh
error: `pre-commit` hook returned 1
```

The pre-commit hook outputs the reason the commit is being rejected, but stg hides it, making it effectively impossible to proceed. The workaround, of course, is to run something like `git ci -m ''`, which shows why the commit was rejected:

```
yamllint.................................................................Failed
- hook id: yamllint
- exit code: 2

vault/overlays/nerc-ocp-test/vault/vault.yaml
  14:1      warning  comment not indented like content  (comments-indentation)
```

It would be nice if `stg` would also expose that information, rather than making me go hunt for it.

**Comment by jpgrayson** [comment]
Thanks for writing up this issue, @larsks. It was indeed a regression in StGit 2.4.3.
