### ISSUE TITLE
RFE: Message-ID support

### ISSUE THREAD

**Issue by awilliam** [stacked-git/stgit#42]
It would be useful if the Message-ID header could be extracted from email imports and optionally included in the commit log.  For example, a new --msgid option to the import command would result in the following being appended to the commit log before any new sign-offs/acks/reviews:
Message-Id: <themessageidextractedfromheader@example.com>

Ideally configuration options might allow the Message-Id string to be changed and the reference to be manipulated (via regex?), such that this same support could generate:
Link: https://lore.kernel.org/r/themessageidextractedfromheader@example.com

This support would align well with better patch tracking that many maintainers are adopting.  Thanks!

**Comment by awilliam** [comment]
Now that stgit uses mailinfo, this is just creating an option to use the -m flag.  A hard coded variant is simply:

diff --git a/stgit/commands/imprt.py b/stgit/commands/imprt.py
index 92c7d59e44fe..0ccd39752473 100644
--- a/stgit/commands/imprt.py
+++ b/stgit/commands/imprt.py
@@ -364,7 +364,7 @@ def __import_mail_path(mail_path, filename, options):
     patch_path = mail_path + '-patch'
 
     mailinfo_lines = (
-        Run('git', 'mailinfo', msg_path, patch_path)
+        Run('git', 'mailinfo', '-m', msg_path, patch_path)
         .encoding(None)
         .decoding(None)
         .raw_input(mail)

**Comment by chucklever** [comment]
Is there a config or cmdline option to disable this behavior?

**Comment by jpgrayson** [comment]
No, should there be?

**Comment by chucklever** [comment]
The Linux kernel subsystem maintainer workflow uses lore, b4, and DKIM attestation, so generally a Message-ID: tag is not required or used. I plan to delete Message-ID: tags after importing patches from mailing lists, at least until such time as Message-ID: becomes a requirement for submitting patches to the Linux kernel. It would save me a step if `stg import` simply skipped adding them.

**Comment by chucklever** [comment]
Well, let me put this a better way. My impression is that when a reference to an e-mail is needed, a kernel commit requires a link to a permanent e-mail archive. Something like:

`Link: https://lore.kernel.org/linux-nfs/163303597560.5125.8905823373792865984.stgit@klimt.1015granger.net/T/#u`

Ah, now that I read the RFE text more closely, I see awilliam was asking for just such a thing.

Anyway, I will have to convert or delete each Message-Id: tag, which takes away some convenience.
