### ISSUE TITLE
"stg pop --spill" leaves patch modifications staged

### ISSUE THREAD

**Issue by palves** [stacked-git/stgit#445]
"stg pop --help" says:

  -s, --spill
          Keep patches' modifications in working tree after popping

But actually running it, it is not what I observe.  Instead, the patches' modifications are left staged / in the index.  "git diff" shows no working tree changes that are not in the index, and "git diff --cached" shows the changes from the patch that was popped.

$ stg version
Stacked Git 2.4.6
Copyright (C) 2005-2024 StGit authors
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
SPDX-License-Identifier: GPL-2.0-only
git version 2.43.2

**Comment by jpgrayson** [comment]
Thank you for this issue report, @palves.

I agree that the behavior of `stg pop --spill` is not quite what the docs indicate. You are right that changes remain in the index and worktree. This works as intended and is consistent with the behavior of `stg spill`.

I will update the documentation for the `--spill` option to clarify the behavior.
