### ISSUE TITLE
feature request: stg whatchanged

### ISSUE THREAD

**Issue by dlan17** [stacked-git/stgit#461]
I'd like to request an equivalent command of "git whatchanged" from stgit, it would much more convenient to show files when the git commit constantly changed.

thanks

**Comment by dlan17** [comment]
as a workaround, "stg show -s" work for me

**Comment by jpgrayson** [comment]
Also `stg files` can be used to just show the files changed by a patch.

And `git log --stat` and `git log --patch` also work well with StGit stacks.

It's not clear to me that a new feature is needed.
