### ISSUE TITLE
feature request: stg move

### ISSUE THREAD

**Issue by dlan17** [stacked-git/stgit#463]
it would be convenient to have a helper command to move changes of files/dir from one series to another, something like this:

stg_move [file or dir] [from_series] [to_series]

stg_move() {
  P=xyz.patch
  if [ -f $1 ] || [ -d $1 ]; then
        git log -p -1 $1 > $P
  fi
  patch -p1 -R < $P
  stg refresh -p $2
  patch -p1 < $P
  git add -A .
  stg refresh -p $3
}

**Comment by jpgrayson** [comment]
`stg spill -- <path...>` can be used to "spill" the changes associated with one or more files or directories from the current patch. The changes remain in the working tree and index though, so they can be put into a new patch or refreshed into another existing patch.

```
stg goto patchX
stg spill -- dir/file dir2
stg refresh -p patchY
```

It's not clear that a new command is needed.
