### ISSUE TITLE
Refresh installation documentation on https://stacked-git.github.io/

### ISSUE THREAD

**Issue by pmolodo** [stacked-git/stgit#465]
The installation instructions available on https://stacked-git.github.io/ apparently are fairly out-of-date (pre 2.0?), as they say you should do:

```sh
make prefix=/usr/local install install-doc
```

...even though the `install-doc` target no longer exists, and the [current INSTALL.md instructions](https://github.com/stacked-git/stgit/blob/v2.4.7/INSTALL.md#full-installation) say to use `install-man` - and were [updated to do so pre-2.0](https://github.com/stacked-git/stgit/commit/64a85a47c5fe2fde47cc06540328ac7839f27261).

**Comment by jpgrayson** [comment]
Thanks for writing this issue, @pmolodo. I've updated the website.

**Comment by pmolodo** [comment]
Awesome, thanks!
