### ISSUE TITLE
Keep the full name of the patch file?

### ISSUE THREAD

**Issue by fjorba** [stacked-git/stgit#489]
First of all, thanks for stacked git. After guilt was left orphaned a while ago, I can do everything I did and, in general, with more flexibility.  One of the few things that I don't like is that stacked git truncates long filenames, and the patch name is left incomplete and sometimes hurting the patch meaning.  So I end up applying my patches this way:

`
$ stg import $dir/$patch && stg rename $patch
`

I'd appreciate either to always keep the original filename or an option to keep it for those of us that prefer this behavior.

**Comment by jpgrayson** [comment]
Try configuring `stgit.namelength`. If it's not set, it defaults to 30. Setting it to 0 should avoid any truncation when the patch filename is mapped to the patch name.

**Comment by fjorba** [comment]
Oh, great. I haven't used any config file. I'm using the .deb package (again, thanks), and I'm interested in having this parameter system wide. Reading the stg manpage, it is not clear to me which file should I use. The same `/etc/gitconfig` than git as I seem to understand this phrase?

 > StGit uses the same configuration mechanism as Git. See git-config(1) for more details.

Excuse my ignorance: should this `stgit.namelength` parmater go straight there, or inside a [clause]?

**Comment by jpgrayson** [comment]
StGit uses your existing git config files.

You can add it to your user account's global configuration with, e.g.:

`git config --global stgit.namelength 0`

Or if you're editing `/etc/gitconfig` manually, you would add a section like this:

```gitconfig
[stgit]
        namelength = 0
```

**Comment by fjorba** [comment]
As I have been able to confirm that this solution works, I close the issue. Thanks.
