### ISSUE TITLE
`stg squash` should preserve the original author when possible

### ISSUE THREAD

**Issue by bonsairobo** [stacked-git/stgit#490]
I just noticed while working on someone else's patches that `stg squash` would overwrite the original author with my identity. I think instead the original author should be preserved and maybe I should be added as an author (or have a CLI flag for it).

**Comment by jpgrayson** [comment]
It sounds like all the patches being squashed had the same author in the scenario you're describing. I've pushed a fix that preserves the consensus author when all patches to be squashed have the same author.

When the patches to be squashed have a mix of authors, I'm not sure there's an obviously correct policy for which author to use/retain. So when the patches to squash have multiple authors, StGit will continue to fallback to using the configured user as the author of the squashed patch.

Note that `stg squash` has `--author`, `--authname`, and `--authemail` options. These are still available and take priority when used.

**Comment by bonsairobo** [comment]
> It sounds like all the patches being squashed had the same author in the scenario you're describing.

Correct. Sorry I was not more specific.

> When the patches to be squashed have a mix of authors, I'm not sure there's an obviously correct policy for which author to use/retain. So when the patches to squash have multiple authors, StGit will continue to fallback to using the configured user as the author of the squashed patch.

That sounds perfectly acceptable.

Maybe it would be nice to have the option to preserve all authors, using [`Co-authored-by` footers](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors). But I'll leave that up to your judgement, it's not something I strongly need.
