### ISSUE TITLE
Incorrect diff for stg mail

### ISSUE THREAD

**Issue by Dovgalyuk** [stacked-git/stgit#62]
When stg mail is executed from non-root directory, diff instead of file statistics contains only "0 files changed".

However, diff includes all the modified lines.

**Comment by jpgrayson** [comment]
Just want to say thank you for submitting this issue. I have not yet tried to reproduce or repair the problem, but I agree that diffs are supposed to work outside the work tree root.

**Comment by jpgrayson** [comment]
Repaired in a622f17.
