### ISSUE TITLE
Use git ref instead of branch for stgit log

### ISSUE THREAD

**Issue by hborchardt** [stacked-git/stgit#65]
I am having the problem that when viewing the repo state in SourceTree, my branch list is cluttered with the `<mybranch>.stgit` log entries from stgit (same argument as Issue #32). 
Instead of not logging at all, would it be possible to not use a branch for the stgit log, but instead an abstract git ref like
`refs/stgitlog/<mybranch>`
to track the state of the log?

I did a quick test changing
https://github.com/stacked-git/stgit/blob/333e9e434cec9aa2f887083cdf2cefcaa316f438/stgit/lib/log.py#L121 
to 
`return 'refs/stgitlog/%s.stgit' % branch `
and as far as I can tell logging, undo, etc. works, as well as having a clean view in SourceTree.

I acknowledge that this would be a breaking change if just edited, so we might want to make the second part of the ref configurable.

If you could confirm that I am not missing anything and you would welcome such a change, I can give a shot at a pull request.

**Comment by hb-aquila** [comment]
I just read your answer in this issue: https://github.com/stacked-git/stgit/issues/24#issuecomment-663738589
I have a feeling that the "old metadata system" refers to the .stgit branch, so waiting for your patch with stackformatversion 4 might solve my problems. If so, feel free to close this issue.

**Comment by jpgrayson** [comment]
Sorry for this delayed response.

To clarify: the old metadata system uses files found under `.git/patches`. The new metadata system uses git objects in the `.stgit` branches. This is contrary to your guess above.

Regarding the idea of using a non-branch ref for the log (metadata), this is actually something I have been considering doing. The reason you site (clutter when using graphical log tools; gitk and even `git log --graph --all` also have this issue) is one of the reasons we might want to use a non-branch ref. Other reasons include:

- The `.stgit` branch can be considered "noise" when using `git branch`
- Checking-out a `.stgit` branch is always a mistake (unless doing stgit development) and thus best to help users avoid this mistake
- Individual patches already have refs found in `.git/refs/patches/<branch>/`.

The potential downsides of _not_ keeping the metadata as a `.stgit` branch include:

- The presence of this branch may be used by StGit users to know that a branch has been initialized (i.e. with `stg init`)
- If we want to support distributed StGit metadata, i.e. pushing and pulling StGit stacks, it may be more intuitive to do this with regular `git` commands if the metadata is a regular branch.

I may be missing other pros/cons. My intent is to experiment with the usability of the metadata being located elsewhere. I was thinking either `refs/stacks/<branch>` or `refs/stgit/<branch>`.

**Comment by hborchardt** [comment]
Much love for implementing this, thanks! ❤️
