### ISSUE TITLE
"stg mail --auto" needs to handle comments in cc: lines

### ISSUE THREAD

**Issue by dhowells** [stacked-git/stgit#91]
There's a common practice on kernel patches to put something like the following in the commit log:

    Cc: stable@vger.kernel.org # v5.10+

but stg mail with --auto fails to handle this, e.g.:

Sending patch "44404" ... mail server refused delivery for the following recipients: {'stable@vger.kernel.org#v5.10+': (501, b'5.1.3 Bad recipient address syntax')}
done

Yes, this is a malformed email address, but, unfortunately, it's not going away.

**Comment by jpgrayson** [comment]
Interesting. It seems like this could be solved by identifying and respecting '#' as the beginning of a comment. This would play out in `__get_signers_list()` in `mail.py`.

A potentially tricky bit is that '#' is allowed in email addresses, at least in the local part (before the '@'), so there is a potential to implement this poorly such that valid email addresses are split or rejected.

Anyway, thanks for identifying this issue. Seems like it should be repaired.

**Comment by jpgrayson** [comment]
FYI, I have a patch in my queue that addresses this issue, but it's behind a few other higher-priority changes and I'm not yet fully happy with my parsing strategy. Suffice that I will have a fix for this eventually.

**Comment by jpgrayson** [comment]
Repaired in 6a948ca.
