### ISSUE TITLE
Feature request: Can --sign/--ack/--review be given an email address as an optional parameter

### ISSUE THREAD

**Issue by dhowells** [stacked-git/stgit#92]
Can it be made such that stg edit --sign/--ack/--review can be given a parameter to indicate the address to be used instead of using the address of whoever's running the command?  E.g.:

   stg edit --sign="David Howells <dhowells@redhat.com>"

**Comment by jpgrayson** [comment]
Under the hood, StGit uses `optparse` for options parsing which does not have built-in support for options with optional arguments. It may be possible to achieve this somehow, but it's not obvious to me how to do it.

A more straightforward alternative would be to have a parallel set of options that required an argument. For example, --sign-as, --ack-as, and --review-as. These could used in the normal manner of GNU-style options, i.e. either with or without `=`:

`stg edit --sign-as="David Howells <dhowells@redhat.com>"` or
`stg edit --sign-as "David Howells <dhowells@redhat.com>"`

I am open to a PR that either adds these new options or somehow figures out how to make an optional argument work with the existing options.

**Comment by dhowells** [comment]
A separate parameter, eg. --sign-as, would be fine.
