### ISSUE TITLE
RFE: "stg import -u" should also handle mbox format

### ISSUE THREAD

**Issue by chucklever** [stacked-git/stgit#94]
The current "stg import" does not support using the "-u" and "-m" flags at the same time. That means pulling a patch from lore.kernel.org is a two-step process:

  $ curl https://lore.kernel.org/linux-iommu/1610376862-927-2-git-send-email-isaacm@codeaurora.org/raw > /tmp/mbox
  $ stg import -n new-patch-name -m /tmp/mbox

It would be a little nicer if it could be a single step, extracting the name of the new patch from the Subject:

  $ stg import -m -u https://lore.kernel.org/linux-iommu/1610376862-927-2-git-send-email-isaacm@codeaurora.org/raw

**Comment by jpgrayson** [comment]
Thanks for this feature idea. I think what you're asking for would be a good feature. And I think the implementation would be reasonably straightforward as well.

A PR would be welcome. Otherwise I will probably work on it eventually.

**Comment by jpgrayson** [comment]
Added this feature in b922a52. Will be in next StGit release.

Thanks again for this idea @chucklever.

**Comment by chucklever** [comment]
Have to say this is an awesome feature. I use it almost every day. Thanks, JP!

**Comment by jpgrayson** [comment]
I appreciate the feedback, @chucklever. And all the help you've given with issue reports!
